### ISSUE TITLE
Historia Usuario 1 - Raven

### ISSUE THREAD

**Issue by alejos17** [alejos17/WebappGanadera#18]
Generar las tareas necesarias para esta historia de Usuario:

"Como Ganadero necesito poder registrarme en la plataforma. "

**Comment by Raveng27** [comment]
Se necesita que el ganadero  implemente su registro al sistema, para tener control sobre el número de ganado bovino de su propiedad y su respectiva información del cuidado veterinario.

**Comment by Raveng27** [comment]
Crear botón login para su respectivo ingreso, con los campos usuario (cédula, Id ganadero) y contraseña (mínimo 8 carácteres alfanuméricos). botón Crear nuevo usuario, con los campos Nombres, apellidos, tipo de ID, número de identificación, año_nacimiento, correo electrónico, teléfono, número móvil, dirección, departamento, municipio, crear contraseña y verificar contraseña.
