### ISSUE TITLE
Mockup - Pagina Inicio

### ISSUE THREAD

**Issue by alejos17** [alejos17/WebappGanadera#26]
Que contenga

- Logo Inicial de la App
- Descripción de la App
- Formulario de Login o Register en la App
- Menú de enlaces a: Ganadero / Veterinario / Ganado / Ejemplares / Vacunas

**Comment by 4ndrezpt** [comment]
Si todos subimos el archivo que genera el balsamiq después podemos juntarlo como si fueran diapositivas en una presentación y revisar que estilo podemos reunir entre todos. 
PD: también subir una captura en la carpeta del drive
![LandingGanaderApp](https://user-images.githubusercontent.com/90282734/135494796-c11384a9-3567-4d9a-af9f-192795040775.png)
