### ISSUE TITLE
Mockup - Veterinario

### ISSUE THREAD

**Issue by alejos17** [alejos17/WebappGanadera#28]
Que contenga

Formulario para registrar o modificar un veterinario
Lista de Veterinarios registrados.
Detalle de Veterinario de cuantas atenciones a realizado.

**Comment by 4ndrezpt** [comment]
![vistaVeterinarios](https://user-images.githubusercontent.com/90282734/135487754-605b4feb-456a-4641-8396-43a3ad6ca2b1.png)
